version: '3.3'

services:
  # PHP-FPM - Service
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: app
    restart: unless-stopped
    tty: true
    working_dir: /var/www

    volumes:
      - ./:/var/www
      - ./docker-files/php/local.ini:/usr/local/etc/php/conf.d/local.ini

    networks:
      - app-network

  # NGINX - Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true

    ports:
      - "9999:80"
      - "8143:443"

    volumes:
      - ./:/var/www
      - ./docker-files/nginx/conf.d/:/etc/nginx/conf.d/

    networks:
      - app-network

  # MariaDB - Service
  db:
    image: mariadb:10.5.6
    container_name: db
    restart: unless-stopped
    tty: true

    ports:
      - "3306:3306"

    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 123456

    volumes:
      - mariadbdata:/var/lib/mysql
      - ./docker-files/mysql/my.cnf:/etc/mysql/my.cnf

    networks:
      - app-network
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "9998:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network

# Volumes
volumes:
  mariadbdata:
    driver: local

# Networks
networks:
  app-network:
    driver: bridge
